### ISSUE TITLE
When resizing the window so it becomes bigger the outline effect gets erased

### ISSUE THREAD

**Issue by AndysonDK** [rexrainbow/phaser3-rex-notes#114]
I think there is a problem with the outline effect plugin or maybe it's a problem with my code.

This is my game initialization code that configures the game:

```JavaScript
import Phaser from 'phaser';
import GameScene from './scenes/GameScene';

const initializeGameInstance = (initialWidth, initialHeight) => (
  new Phaser.Game({
    type: Phaser.AUTO,
    width: initialWidth,
    height: initialHeight,
    parent: 'phaser-container',
    scale: {
      // Could've used FIT but this seems to work better, because it takes the following user action into account:
      // Resize very fast
      mode: Phaser.Scale.WIDTH_CONTROLS_HEIGHT
    },
    physics: {
      default: 'arcade',
      arcade: {
        debug: true
      }
    },
    scene: [GameScene]
  })
);

export const prepareFullscreen = game => {
  // This is to make sure that phaser doesn't scale the canvas automatically
  game.scale.scaleMode = Phaser.Scale.NONE;
  
  // Remove all the applied inline styling on the canvas element
  game.canvas.removeAttribute("style");
  
  // Refresh so the disabled scaling takes affect
  game.scale.refresh();
};

export const cleanUpFullscreen = game => {
  // This is to make sure phaser falls back to the first setting to automatically scale the canvas
  game.scale.scaleMode = Phaser.Scale.WIDTH_CONTROLS_HEIGHT;

  // Refresh so the enabled scaling takes affect
  game.scale.refresh();
};

export default initializeGameInstance;
```

This is the code where I'm using the outline effect plugin (https://rexrainbow.github.io/phaser3-rex-notes/docs/site/effectlayer-outline/):

```JavaScript
import Phaser from 'phaser';
import OutlineEffectLayer from 'phaser3-rex-plugins/plugins/outlineeffectlayer.js';
import BuildArcadeObject from 'phaser3-rex-plugins/plugins/buildarcadeobject.js';
import CircleMaskImage from 'phaser3-rex-plugins/plugins/circlemaskimage.js';

export default class GameScene extends Phaser.Scene {
  constructor() {
    super('main');
    this.player = undefined;
    this.cursors = undefined;
  }

  preload() {
    this.load.image('pfp', 'some external image url that has a size of (160 x 160) pixels');
  }
  
  create() {
    const graphics = this.add.graphics();

    graphics.fillGradientStyle(0x0479c3, 0x0479c3, 0x00e0ff, 0x00e0ff);
    graphics.fillRect(0, 0, 4000, 4000);
    
    const grid = this.add.grid(0, 0, 4000, 4000, 64, 64, null, null, 0xA0A0A0);
    grid.setOrigin(0);
    
    this.physics.world.setBounds(500, 500, 3000, 3000);
    
    // circle mask image -- begin
    const image = new CircleMaskImage(this, 1750, 1750, 'pfp');
    this.add.existing(image);
    // circle mask image -- end
    
    // outline -- begin
    const effectLayer = new OutlineEffectLayer(this, {thickness: 8, outlineColor: 0x33FF48});
    this.add.existing(effectLayer);
    effectLayer.add(image);
    // outline -- end
    
    this.player = BuildArcadeObject(image);
    this.player.setCircle(80);
    this.player.setCollideWorldBounds(true);
    
    this.cameras.main.setBounds(0, 0, 4000, 4000);
    this.cameras.main.startFollow(this.player, true);
    
    this.cursors = this.input.keyboard.createCursorKeys();
  }

  update() {
    if (this.cursors.left.isDown) this.player.setVelocityX(-160);
    else if (this.cursors.right.isDown) this.player.setVelocityX(160);
    else this.player.setVelocityX(0);

    if (this.cursors.down.isDown) this.player.setVelocityY(160);
    else if (this.cursors.up.isDown) this.player.setVelocityY(-160);
    else this.player.setVelocityY(0);
  }
```

When I make a call to the resize method on the scalemanager where `scaledWidth` and `scaledHeight` are high in value:

```JavaScript
const scaledWidth = Math.floor(window.innerWidth * window.devicePixelRatio);
const scaledHeight = Math.floor(window.innerHeight * window.devicePixelRatio);

game.current.scale.resize(scaledWidth, scaledHeight);
```
Some of the outline effect gets erased apparently

But if I zoom in manually by pressing `ctrl + mouse scroll wheel`
The outline effect comes back again, pretty weird.

This is how it looks like when some of the outline effect has been erased:
<img width="1077" alt="Anmærkning 2020-08-04 111903" src="https://user-images.githubusercontent.com/28491857/89278619-a73bf280-d646-11ea-9426-fd7a195ae7df.png">

If I resize the screen even more this happens:
<img width="1135" alt="Anmærkning 2020-08-04 112323" src="https://user-images.githubusercontent.com/28491857/89277281-ed905200-d644-11ea-8584-d6b0d17d7913.png">

And when resized enough no outline effect can be seen anymore:
<img width="1260" alt="Anmærkning 2020-08-04 112414" src="https://user-images.githubusercontent.com/28491857/89277361-08fb5d00-d645-11ea-9662-9f11acf27523.png">

This is how it looks like when I zoom in after I have resized the window a lot, you can see that the outline effect has come back again:
<img width="1265" alt="Anmærkning 2020-08-04 113213" src="https://user-images.githubusercontent.com/28491857/89278252-2846ba00-d646-11ea-9ad7-32b09b5642b2.png">

And this is how it looks like when I haven't resized the window very much:
<img width="934" alt="Anmærkning 2020-08-04 113355" src="https://user-images.githubusercontent.com/28491857/89278492-7956ae00-d646-11ea-9462-4f3db57c198b.png">

**Comment by rexrainbow** [comment]
Size of outline effect game object is fixed when creating, to cover whole visible area. This size won't changed after resizing currently. I can add this feature later.

**Comment by rexrainbow** [comment]
Feature added. 
[Here](https://codepen.io/rexrainbow/pen/GRZRNYJ) is a demo, game size is (100,100) at beginning, set to (800, 600) after creating Outline effect game object.

**Comment by AndysonDK** [comment]
Still doesn't seem to work for me by using the imported npm package, could you update the npm package with the new changes?

**Comment by rexrainbow** [comment]
Upgraded.

**Comment by AndysonDK** [comment]
Awesome it works now, thanks for your time!
